import { MatchType } from "@prisma/client";

export interface DemoMatch {
  id: string;
  name: string;
  description?: string | null;
  location?: string | null;
  isHome?: boolean | null;
  matchUrl?: string | null;
  kitColor?: string | null;
  shirtNumber?: string | null;
  position?: string | null;
  minutesPlayed?: string | null;
  date: Date;
  startTime?: string | null;
  endTime?: string | null;
  opponent?: string | null;
  category?: string | null;
  leaguePosition?: string | null;
  matchType: MatchType;
  competitionType?: string | null;
  playerKey: string;
  trainerKey?: string | null;
  teamId?: string | null;
  mark?: number | null;
  intensity?: number | null;
  attitude?: number | null;
  performance?: number | null;
  goals?: number | null;
  assists?: number | null;
  strengths: string[];
  weaknesses: string[];
  improvementAreas: string[];
  comment?: string | null;
  trainerFeedback?: string | null;
  playerReflection?: string | null;
  isReviewed: boolean;
  reviewedAt?: Date | null;
}

export interface DemoFeedbackMessage {
  id: string;
  matchId: string;
  authorKey: string;
  authorRole: string;
  content: string;
  createdAt: Date;
}

export const DEMO_MATCHES: DemoMatch[] = [
  // --- Original Matches ---
  {
    id: "seed-match-league-real-madrid",
    name: "League Match vs Real Madrid",
    description: "Tough match at home stadium. High pressure game.",
    location: "Metropolitano",
    isHome: true,
    matchUrl: "https://www.youtube.com/watch?v=mock1",
    kitColor: "Red",
    shirtNumber: "10",
    position: "Midfielder",
    minutesPlayed: "90",
    date: new Date(), // Today
    startTime: "18:00",
    endTime: "19:45",
    opponent: "Real Madrid",
    category: "First Team",
    leaguePosition: "2nd",
    matchType: MatchType.LEAGUE,
    competitionType: "La Liga",
    playerKey: "player",
    trainerKey: "trainer",
    teamId: "team_001",
    mark: 8,
    intensity: 9,
    attitude: 10,
    performance: 8,
    goals: 1,
    assists: 1,
    strengths: ["Great positioning", "Assisted the winning goal"],
    weaknesses: ["A bit tired in the last 10 minutes"],
    improvementAreas: ["Aerobic capacity"],
    comment: "Good control in midfield, drove the team forward.",
    trainerFeedback: "Excellent tactical discipline today.",
    playerReflection: "Felt strong in the first half, need to manage stamina better in the end.",
    isReviewed: true,
    reviewedAt: new Date(),
  },
  {
    id: "seed-match-friendly-getafe",
    name: "Friendly Match vs Getafe",
    description: "Training friendly game to try new tactics.",
    location: "Getafe Training Camp",
    isHome: false,
    matchUrl: "https://www.youtube.com/watch?v=mock2",
    kitColor: "White",
    shirtNumber: "14",
    position: "Sub",
    minutesPlayed: "30",
    date: new Date(Date.now() + 24 * 60 * 60 * 1000), // Tomorrow
    startTime: "11:00",
    endTime: "12:30",
    opponent: "Getafe CF",
    category: "First Team",
    leaguePosition: "2nd",
    matchType: MatchType.FRIENDLY,
    competitionType: "Friendly",
    playerKey: "player",
    trainerKey: "trainer",
    teamId: "team_001",
    mark: null,
    intensity: null,
    attitude: null,
    performance: null,
    goals: 0,
    assists: 0,
    strengths: [],
    weaknesses: [],
    improvementAreas: [],
    comment: null,
    trainerFeedback: null,
    playerReflection: null,
    isReviewed: false,
    reviewedAt: null,
  },

  // --- Past reviewed matches ---
  {
    id: "seed-match-cup-barcelona",
    name: "Copa del Rey vs FC Barcelona",
    description: "Quarter-finals Copa del Rey. High stakes match.",
    location: "Camp Nou",
    isHome: false,
    matchUrl: "https://www.youtube.com/watch?v=mock_barca",
    kitColor: "White",
    shirtNumber: "10",
    position: "Midfielder",
    minutesPlayed: "90",
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
    startTime: "21:00",
    endTime: "22:45",
    opponent: "FC Barcelona",
    category: "First Team",
    leaguePosition: "N/A",
    matchType: MatchType.CUP,
    competitionType: "Copa del Rey",
    playerKey: "player",
    trainerKey: "trainer",
    teamId: "team_001",
    mark: 9,
    intensity: 9,
    attitude: 10,
    performance: 9,
    goals: 2,
    assists: 1,
    strengths: ["Clinical finishing in the second goal", "High recovery rate in midfield", "Excellent link-up play"],
    weaknesses: ["Muscle tightness towards the end", "Lost two aerial duels in our box"],
    improvementAreas: ["Conditioning recovery", "Defensive headers"],
    comment: "Outstanding performance. Controlled the tempo of the game and scored the decisive goals.",
    trainerFeedback: "World-class performance under pressure. Your decision-making in transition was top notch.",
    playerReflection: "Extremely happy with my performance. I felt very confident on the ball, though my hamstrings felt a bit loaded after the 80th minute.",
    isReviewed: true,
    reviewedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: "seed-match-training-session-1",
    name: "Tactical training & Stamina",
    description: "Focus on build-up play from the back and high intensity aerobic drills.",
    location: "Pitch 3 - Training Ground",
    isHome: true,
    matchUrl: null,
    kitColor: "Red",
    shirtNumber: "10",
    position: "Midfielder",
    minutesPlayed: "75",
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
    startTime: "10:00",
    endTime: "11:15",
    opponent: "Team B (Internal)",
    category: "First Team",
    leaguePosition: "N/A",
    matchType: MatchType.TRAINING,
    competitionType: "Training",
    playerKey: "player",
    trainerKey: "trainer",
    teamId: "team_001",
    mark: 8,
    intensity: 8,
    attitude: 9,
    performance: 8,
    goals: 0,
    assists: 0,
    strengths: ["Solid passing rhythm", "Good tactical understanding during drills"],
    weaknesses: ["Slow recovery sprint on one occasion"],
    improvementAreas: ["Sprint endurance"],
    comment: "Good session. Showed great attitude and led the build-up exercises.",
    trainerFeedback: "Very focused today. The passing accuracy was excellent.",
    playerReflection: "Felt good physically, recovering well from the cup game. The tactical drills helped me understand the positioning better.",
    isReviewed: true,
    reviewedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "seed-match-league-sevilla-gk",
    name: "League Match vs Sevilla FC",
    description: "Crucial league match to keep the clean sheet record.",
    location: "Metropolitano",
    isHome: true,
    matchUrl: "https://www.youtube.com/watch?v=mock_sevilla",
    kitColor: "Green",
    shirtNumber: "1",
    position: "Goalkeeper",
    minutesPlayed: "90",
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
    startTime: "19:00",
    endTime: "20:45",
    opponent: "Sevilla FC",
    category: "First Team",
    leaguePosition: "2nd",
    matchType: MatchType.LEAGUE,
    competitionType: "La Liga",
    playerKey: "goalkeeper",
    trainerKey: "trainer",
    teamId: "team_001",
    mark: 7,
    intensity: 7,
    attitude: 8,
    performance: 8,
    goals: 0,
    assists: 0,
    strengths: ["Excellent aerial command", "Two key reflex saves", "Clean sheet maintained"],
    weaknesses: ["One poor distribution pass under pressure"],
    improvementAreas: ["Distribution with non-dominant foot"],
    comment: "Solid performance. Kept us in the game during the first half.",
    trainerFeedback: "Very secure on crosses today. Keep working on the short distribution.",
    playerReflection: "Felt very secure. Working on crosses in training paid off.",
    isReviewed: true,
    reviewedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "seed-match-cup-valencia-p3",
    name: "Copa del Rey vs Valencia CF",
    description: "Valencia away. Tough environment.",
    location: "Mestalla",
    isHome: false,
    matchUrl: "https://www.youtube.com/watch?v=mock_valencia",
    kitColor: "White",
    shirtNumber: "9",
    position: "Striker",
    minutesPlayed: "80",
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000), // 4 days ago
    startTime: "20:00",
    endTime: "21:45",
    opponent: "Valencia CF",
    category: "First Team",
    leaguePosition: "N/A",
    matchType: MatchType.CUP,
    competitionType: "Copa del Rey",
    playerKey: "player-3",
    trainerKey: "trainer",
    teamId: "team_001",
    mark: 8,
    intensity: 8,
    attitude: 8,
    performance: 8,
    goals: 1,
    assists: 0,
    strengths: ["Great run behind the defense for the goal", "Good defensive pressing"],
    weaknesses: ["Missed a clear chance in the 15th minute"],
    improvementAreas: ["Finishing composure"],
    comment: "Good striker movement. Always a threat.",
    trainerFeedback: "Great effort, your runs created lots of spaces for the midfielders.",
    playerReflection: "Happy with the goal but I should have scored the early one.",
    isReviewed: true,
    reviewedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: "seed-match-league-villarreal-p5",
    name: "League Match vs Villarreal CF",
    description: "Away game. Technical match against a ball-dominant team.",
    location: "Estadio de la Cerámica",
    isHome: false,
    matchUrl: "https://www.youtube.com/watch?v=mock_villarreal",
    kitColor: "White",
    shirtNumber: "8",
    position: "Midfielder",
    minutesPlayed: "85",
    date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000), // 6 days ago
    startTime: "16:00",
    endTime: "17:45",
    opponent: "Villarreal CF",
    category: "First Team",
    leaguePosition: "3rd",
    matchType: MatchType.LEAGUE,
    competitionType: "La Liga",
    playerKey: "player-5",
    trainerKey: "trainer-2",
    teamId: "team_002",
    mark: 9,
    intensity: 8,
    attitude: 9,
    performance: 9,
    goals: 0,
    assists: 2,
    strengths: ["Brilliant build-up assists", "100% dribbling success rate", "Controlled the midfield completely"],
    weaknesses: ["One tactical foul given away in dangerous area"],
    improvementAreas: ["Defensive transition speed"],
    comment: "Masterclass in midfield control. Provided two beautiful assists.",
    trainerFeedback: "Superb vision. You made the game look simple today.",
    playerReflection: "I felt very comfortable. Found the right spaces between their lines.",
    isReviewed: true,
    reviewedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },

  // --- Future matches ---
  {
    id: "seed-match-league-atletico",
    name: "League Match vs Atlético de Madrid",
    description: "Big derby match. Very important for the league table standings.",
    location: "Metropolitano",
    isHome: true,
    matchUrl: null,
    kitColor: "Red",
    shirtNumber: "10",
    position: "Midfielder",
    minutesPlayed: null,
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
    startTime: "21:00",
    endTime: "22:45",
    opponent: "Atlético de Madrid",
    category: "First Team",
    leaguePosition: "2nd",
    matchType: MatchType.LEAGUE,
    competitionType: "La Liga",
    playerKey: "player",
    trainerKey: "trainer",
    teamId: "team_001",
    mark: null,
    intensity: null,
    attitude: null,
    performance: null,
    goals: 0,
    assists: 0,
    strengths: [],
    weaknesses: [],
    improvementAreas: [],
    comment: null,
    trainerFeedback: null,
    playerReflection: null,
    isReviewed: false,
    reviewedAt: null,
  },
  {
    id: "seed-match-friendly-rayo-gk",
    name: "Friendly Match vs Rayo Vallecano",
    description: "Mid-season friendly match to give players extra rhythm.",
    location: "Vallecas",
    isHome: false,
    matchUrl: null,
    kitColor: "Green",
    shirtNumber: "1",
    position: "Goalkeeper",
    minutesPlayed: null,
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), // 3 days from now
    startTime: "12:00",
    endTime: "13:45",
    opponent: "Rayo Vallecano",
    category: "First Team",
    leaguePosition: "2nd",
    matchType: MatchType.FRIENDLY,
    competitionType: "Friendly",
    playerKey: "goalkeeper",
    trainerKey: "trainer",
    teamId: "team_001",
    mark: null,
    intensity: null,
    attitude: null,
    performance: null,
    goals: 0,
    assists: 0,
    strengths: [],
    weaknesses: [],
    improvementAreas: [],
    comment: null,
    trainerFeedback: null,
    playerReflection: null,
    isReviewed: false,
    reviewedAt: null,
  },
  {
    id: "seed-match-league-betis-p3",
    name: "League Match vs Real Betis",
    description: "Regular season league match.",
    location: "Benito Villamarín",
    isHome: false,
    matchUrl: null,
    kitColor: "White",
    shirtNumber: "9",
    position: "Striker",
    minutesPlayed: null,
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000), // 5 days from now
    startTime: "18:30",
    endTime: "20:15",
    opponent: "Real Betis",
    category: "First Team",
    leaguePosition: "3rd",
    matchType: MatchType.LEAGUE,
    competitionType: "La Liga",
    playerKey: "player-3",
    trainerKey: "trainer",
    teamId: "team_001",
    mark: null,
    intensity: null,
    attitude: null,
    performance: null,
    goals: 0,
    assists: 0,
    strengths: [],
    weaknesses: [],
    improvementAreas: [],
    comment: null,
    trainerFeedback: null,
    playerReflection: null,
    isReviewed: false,
    reviewedAt: null,
  },
];

export const DEMO_FEEDBACK_MESSAGES: DemoFeedbackMessage[] = [
  // --- Thread 1: Main player vs Main trainer on Barca Cup match ---
  {
    id: "seed-fb-msg-1",
    matchId: "seed-match-cup-barcelona",
    authorKey: "trainer",
    authorRole: "trainer",
    content: "Excelente partido el de la Copa, hiciste un gran desgaste físico y la definición en el segundo gol fue de clase mundial. Sigue así.",
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000),
  },
  {
    id: "seed-fb-msg-2",
    matchId: "seed-match-cup-barcelona",
    authorKey: "player",
    authorRole: "player",
    content: "¡Gracias míster! Sentí buenas sensaciones físicas durante todo el partido, aunque al final el gemelo se me cargó un poco. ¿Crees que debería dosificar en el próximo entrenamiento?",
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000),
  },
  {
    id: "seed-fb-msg-3",
    matchId: "seed-match-cup-barcelona",
    authorKey: "trainer",
    authorRole: "trainer",
    content: "Sí, he hablado con el preparador físico para que hagas trabajo regenerativo suave mañana. No arriesguemos.",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: "seed-fb-msg-4",
    matchId: "seed-match-cup-barcelona",
    authorKey: "player",
    authorRole: "player",
    content: "De acuerdo, nos vemos mañana en el gimnasio.",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 1 * 60 * 60 * 1000),
  },

  // --- Thread 2: Goalkeeper vs Main trainer on Sevilla match ---
  {
    id: "seed-fb-msg-gk-1",
    matchId: "seed-match-league-sevilla-gk",
    authorKey: "trainer",
    authorRole: "trainer",
    content: "Gran portería a cero ante el Sevilla. Muy seguro en las salidas aéreas.",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "seed-fb-msg-gk-2",
    matchId: "seed-match-league-sevilla-gk",
    authorKey: "goalkeeper",
    authorRole: "goal_keeper",
    content: "Gracias míster. He estado trabajando en el posicionamiento de los centros laterales con el preparador de porteros y se notó la mejoría.",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000),
  },
];
